# Generated by Django 5.1.1 on 2024-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Self',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('self_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('telegram_id', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50, null=True)),
                ('refresh_token', models.CharField(max_length=50, null=True)),
                ('token_expiration', models.DateTimeField()),
            ],
        ),
    ]
