# Generated by Django 5.1.1 on 2024-10-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='token_expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
