# Generated by Django 5.1.1 on 2024-10-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0002_alter_useraccount_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='self',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='self', to='UserAccount.useraccount'),
            preserve_default=False,
        ),
    ]
