# Generated by Django 5.1.1 on 2024-10-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_self_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='self',
            name='account',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='self',
            field=models.ManyToManyField(to='UserAccount.self'),
        ),
    ]
